server:
  port: 7448
  servlet:
    context-path: /HIS
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: shivdahale2412@gmail.com
    password: 744826spd...
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetime: 5000
          starttls:
            enable: true
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: system
    password: manager
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true      